# Production deployment configuration for Grid-Fed-RL-Gym
# Autonomous SDLC v4.0 - Generated Configuration

apiVersion: v1
kind: Config
metadata:
  name: grid-fed-rl-production
  version: "0.1.0"
  generated_by: "Autonomous SDLC v4.0"
  timestamp: "2025-01-25"

# Application Configuration
application:
  name: grid-fed-rl-gym
  version: "0.1.0"
  description: "Digital twin framework for power distribution networks with federated offline RL"
  maintainer: "daniel@terragonlabs.com"
  
  # Runtime settings
  runtime:
    python_version: "3.9+"
    memory_limit: "2Gi"
    cpu_limit: "2000m"
    replicas: 3
    health_check_interval: 30
    graceful_shutdown_timeout: 30
  
  # Performance settings
  performance:
    cache_size_mb: 500
    max_workers: 8
    connection_pool_size: 20
    request_timeout: 300
    max_concurrent_requests: 100

# Infrastructure Configuration
infrastructure:
  # Container settings
  container:
    base_image: "python:3.11-slim"
    registry: "docker.io"
    repository: "terragonlabs/grid-fed-rl-gym"
    tag: "latest"
    pull_policy: "Always"
  
  # Resource requirements
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "2Gi"  
      cpu: "2000m"
    storage: "10Gi"

  # Scaling configuration
  autoscaling:
    enabled: true
    min_replicas: 2
    max_replicas: 10
    target_cpu_utilization: 70
    target_memory_utilization: 80

# Security Configuration
security:
  # Network policies
  network:
    ingress_enabled: true
    egress_rules:
      - allow_dns: true
      - allow_external_apis: true
      - block_internal_networks: true
  
  # Authentication & Authorization
  auth:
    method: "api_key"
    token_expiry: 3600
    rate_limiting:
      requests_per_minute: 1000
      burst_size: 100
  
  # Input validation
  validation:
    level: "strict"
    sanitize_input: true
    max_input_size: "10MB"
    allowed_file_types: [".json", ".yaml", ".csv"]

# Monitoring & Observability
monitoring:
  # Health checks
  health_checks:
    liveness_probe:
      path: "/health"
      initial_delay: 30
      period: 10
      timeout: 5
      failure_threshold: 3
    
    readiness_probe:
      path: "/ready"
      initial_delay: 5
      period: 5
      timeout: 3
      failure_threshold: 3

  # Metrics
  metrics:
    enabled: true
    port: 9090
    path: "/metrics"
    scrape_interval: 15
    retention_days: 30
  
  # Logging
  logging:
    level: "INFO"
    format: "json"
    max_file_size: "100MB"
    max_files: 10
    destinations: ["stdout", "file", "external"]

# Data & Storage
storage:
  # Persistent volumes
  persistent:
    enabled: true
    size: "10Gi"
    access_mode: "ReadWriteOnce"
    storage_class: "ssd"
  
  # Cache storage
  cache:
    type: "redis"
    size: "1Gi"
    ttl_default: 3600
    max_memory_policy: "allkeys-lru"
  
  # Backup configuration
  backup:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    retention_days: 30
    compression: true

# Environment Configuration
environment:
  # Production environment variables
  variables:
    ENVIRONMENT: "production"
    LOG_LEVEL: "INFO"
    CACHE_SIZE_MB: "500"
    MAX_WORKERS: "8"
    HEALTH_CHECK_ENABLED: "true"
    PERFORMANCE_MONITORING: "true"
    INPUT_VALIDATION_LEVEL: "strict"
    ENABLE_METRICS: "true"
    GRACEFUL_SHUTDOWN: "true"
  
  # Secrets (to be provided externally)
  secrets:
    - name: "api-keys"
      keys: ["primary_key", "backup_key"]
    - name: "database-credentials" 
      keys: ["username", "password", "connection_string"]
    - name: "external-api-tokens"
      keys: ["research_api_token", "monitoring_token"]

# Service Configuration
service:
  # API endpoints
  api:
    port: 8080
    prefix: "/api/v1"
    cors_enabled: true
    rate_limiting: true
    
  # Load balancer
  load_balancer:
    type: "nginx"
    algorithm: "round_robin"
    session_affinity: false
    health_check_path: "/health"
  
  # Service mesh (optional)
  service_mesh:
    enabled: false
    type: "istio"
    mutual_tls: true

# Quality Gates Configuration
quality_gates:
  # Pre-deployment checks
  pre_deployment:
    - security_scan
    - vulnerability_assessment
    - performance_benchmark
    - integration_tests
    - smoke_tests
  
  # Post-deployment validation
  post_deployment:
    - health_check_validation
    - performance_regression_test
    - security_validation
    - monitoring_validation
  
  # Rollback triggers
  rollback_triggers:
    - error_rate_threshold: 5%
    - response_time_threshold: 1000ms
    - availability_threshold: 99.9%
    - memory_usage_threshold: 90%

# Global Configuration
global:
  # Multi-region settings
  regions:
    primary: "us-west-2"
    secondary: ["us-east-1", "eu-west-1"]
    disaster_recovery: "us-central-1"
  
  # Internationalization
  i18n:
    default_language: "en"
    supported_languages: ["en", "es", "fr", "de", "ja", "zh"]
    timezone_support: true
    localization_enabled: true
  
  # Performance benchmarks
  benchmarks:
    response_time_p99: "200ms"
    throughput_rps: 1000
    availability_target: "99.95%"
    error_rate_max: "0.1%"